/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.tala;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class TestObject extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4974837279523001716L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TestObject\",\"namespace\":\"com.tala\",\"fields\":[{\"name\":\"someLong\",\"type\":\"long\"},{\"name\":\"number\",\"type\":[\"null\",\"int\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TestObject> ENCODER =
      new BinaryMessageEncoder<TestObject>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TestObject> DECODER =
      new BinaryMessageDecoder<TestObject>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<TestObject> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<TestObject> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<TestObject> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<TestObject>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this TestObject to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a TestObject from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a TestObject instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static TestObject fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private long someLong;
   private java.lang.Integer number;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TestObject() {}

  /**
   * All-args constructor.
   * @param someLong The new value for someLong
   * @param number The new value for number
   */
  public TestObject(java.lang.Long someLong, java.lang.Integer number) {
    this.someLong = someLong;
    this.number = number;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return someLong;
    case 1: return number;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: someLong = (java.lang.Long)value$; break;
    case 1: number = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'someLong' field.
   * @return The value of the 'someLong' field.
   */
  public long getSomeLong() {
    return someLong;
  }


  /**
   * Sets the value of the 'someLong' field.
   * @param value the value to set.
   */
  public void setSomeLong(long value) {
    this.someLong = value;
  }

  /**
   * Gets the value of the 'number' field.
   * @return The value of the 'number' field.
   */
  public java.lang.Integer getNumber() {
    return number;
  }


  /**
   * Sets the value of the 'number' field.
   * @param value the value to set.
   */
  public void setNumber(java.lang.Integer value) {
    this.number = value;
  }

  /**
   * Creates a new TestObject RecordBuilder.
   * @return A new TestObject RecordBuilder
   */
  public static com.tala.TestObject.Builder newBuilder() {
    return new com.tala.TestObject.Builder();
  }

  /**
   * Creates a new TestObject RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TestObject RecordBuilder
   */
  public static com.tala.TestObject.Builder newBuilder(com.tala.TestObject.Builder other) {
    if (other == null) {
      return new com.tala.TestObject.Builder();
    } else {
      return new com.tala.TestObject.Builder(other);
    }
  }

  /**
   * Creates a new TestObject RecordBuilder by copying an existing TestObject instance.
   * @param other The existing instance to copy.
   * @return A new TestObject RecordBuilder
   */
  public static com.tala.TestObject.Builder newBuilder(com.tala.TestObject other) {
    if (other == null) {
      return new com.tala.TestObject.Builder();
    } else {
      return new com.tala.TestObject.Builder(other);
    }
  }

  /**
   * RecordBuilder for TestObject instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TestObject>
    implements org.apache.avro.data.RecordBuilder<TestObject> {

    private long someLong;
    private java.lang.Integer number;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.tala.TestObject.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.someLong)) {
        this.someLong = data().deepCopy(fields()[0].schema(), other.someLong);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.number)) {
        this.number = data().deepCopy(fields()[1].schema(), other.number);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing TestObject instance
     * @param other The existing instance to copy.
     */
    private Builder(com.tala.TestObject other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.someLong)) {
        this.someLong = data().deepCopy(fields()[0].schema(), other.someLong);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.number)) {
        this.number = data().deepCopy(fields()[1].schema(), other.number);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'someLong' field.
      * @return The value.
      */
    public long getSomeLong() {
      return someLong;
    }


    /**
      * Sets the value of the 'someLong' field.
      * @param value The value of 'someLong'.
      * @return This builder.
      */
    public com.tala.TestObject.Builder setSomeLong(long value) {
      validate(fields()[0], value);
      this.someLong = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'someLong' field has been set.
      * @return True if the 'someLong' field has been set, false otherwise.
      */
    public boolean hasSomeLong() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'someLong' field.
      * @return This builder.
      */
    public com.tala.TestObject.Builder clearSomeLong() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'number' field.
      * @return The value.
      */
    public java.lang.Integer getNumber() {
      return number;
    }


    /**
      * Sets the value of the 'number' field.
      * @param value The value of 'number'.
      * @return This builder.
      */
    public com.tala.TestObject.Builder setNumber(java.lang.Integer value) {
      validate(fields()[1], value);
      this.number = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'number' field has been set.
      * @return True if the 'number' field has been set, false otherwise.
      */
    public boolean hasNumber() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'number' field.
      * @return This builder.
      */
    public com.tala.TestObject.Builder clearNumber() {
      number = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TestObject build() {
      try {
        TestObject record = new TestObject();
        record.someLong = fieldSetFlags()[0] ? this.someLong : (java.lang.Long) defaultValue(fields()[0]);
        record.number = fieldSetFlags()[1] ? this.number : (java.lang.Integer) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TestObject>
    WRITER$ = (org.apache.avro.io.DatumWriter<TestObject>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TestObject>
    READER$ = (org.apache.avro.io.DatumReader<TestObject>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.someLong);

    if (this.number == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeInt(this.number);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.someLong = in.readLong();

      if (in.readIndex() != 1) {
        in.readNull();
        this.number = null;
      } else {
        this.number = in.readInt();
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.someLong = in.readLong();
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.number = null;
          } else {
            this.number = in.readInt();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










